server:
  port: 58080
spring:
  application:
    name: ${app_name:examples-rocketmq}

  # 数据源 ######################################################################################################################
  # Spring Boot 配置
  datasource:
    # Druid 数据源配置
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: org.sqlite.JDBC
    # SQLite 数据库路径（支持绝对路径和相对路径）
    #url: jdbc:sqlite:E:\DiGuaPao\gitee\diguapao-cloud\examples-collection\examples-java\examples-rocketmq\e-rocketmq-spring-boot-starter\src\main\resources\db\database_sqlite_examples_rocketmq_order.db?busy_timeout=5000
    # 或者使用内存数据库
    # url: jdbc:sqlite::memory
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/DiGuaPao/gitee/diguapao-cloud/examples-collection/examples-java/examples-rocketmq/e-rocketmq-spring-boot-starter/data/examples_rocketmq_order_${server.port}_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""

#  # 使用H2时可启用 schema.sql 自动执行（必须！）
#  sql:
#    init:
#      mode: always  # 总是执行初始化脚本
#      schema-locations: classpath:schema.sql
#       data-locations: classpath:data.sql   # 如果有初始数据

    # Druid 连接池配置
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 获取连接等待超时时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql
      validation-query: SELECT 1
      validationQuery: SELECT 1
      # 建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

      filter:
        wall:
          enabled: true
          dbTypeName: mysql
          config:
            dbType: mysql
            deleteAllow: true  # 允许 DELETE 语句
            insertAllow: true  # 允许 INSERT 语句
            multiStatementAllow: true  # 允许执行多条 SQL 语句
        stat:
          enabled: true
          dbType: mysql
          logSlowSql: true # 是否记录慢 SQL，默认为 false
          slowSqlMillis: 500 # 慢 SQL 的阈值，单位毫秒
          slowSqlLogLevel: WARN # 将慢SQL日志级别从error改为warn
          mergeSql: true # 是否合并 SQL，默认为 false
          resetAggrTable: false # 是否重置聚合统计表，每次启动时都会清空，默认为 false
          multiStatementAllow: true # 允许执行多条 sql
        log4j2:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      log-filter:
        statement:
          sql-pretty-format: false
      log:
        stmt-exec-sql-log-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: '/*'
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        login-username: ''
        login-password: ''
        allow: 0.0.0.0
        deny: ''

  h2:
    console:
      enabled: true
      path: /h2-console

# MyBatis Plus 配置
mybatis-plus:
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: org.diguapao.cloud.framework.rocketmq.core.entity
  # mapper.xml文件位置
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    # 自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 主键类型 AUTO=数据库自增 NONE=无 INPUT=自行输入 ASSIGN_ID=雪花算法 ASSIGN_UUID=UUID
      id-type: AUTO
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

logging.level.org.apache.rocketmq: info


#### producer & consumer 通用配置
rocketmq.name-server: localhost:9876;localhost:19876;localhost:29876


#### producer 配置
rocketmq.producer.group: ${spring.application.name}-group
# mqadmin.cmd updateTopic -n localhost:9876;localhost:19876;localhost:29876 -t examples-rocketmq-topic -c DefaultCluster
rocketmq.producer.examples.rocketmq.topic: examples-rocketmq-topic
rocketmq.producer.order.sub.topic: order-sub-topic
# 访问控制配置
rocketmq.producer.access-key: producer_user
rocketmq.producer.secret-key: producer123
rocketmq.producer.send-message-timeout: 15000
# 出现问题：invokeSync call the addr[127.0.0.1:19876] timeout，可添加rocketmq.producer.mq-client-api-timeout参数去解决，只是很奇怪，本地部署的集群，默认的3秒就是会超时
# 该参数需要二开rocketmq-spring-boot在org.apache.rocketmq.spring.autoconfigure.RocketMQProperties中新增，还需完善org.apache.rocketmq.spring.autoconfigure包下的自动配置
rocketmq.producer.mq-client-api-timeout: 15000


#### consumer 配置
rocketmq.consumer.topic: ${spring.application.name}-topic
rocketmq.consumer.group: ${spring.application.name}-group
rocketmq.consumer.examples.rocketmq.topic: examples-rocketmq-topic
# mqadmin.cmd updateSubGroup -n localhost:9876;localhost:19876;localhost:29876 -g examples-rocketmq-group -c DefaultCluster
rocketmq.consumer.examples.rocketmq.group: examples-rocketmq-group
rocketmq.consumer.order.sub.topic: order-sub-topic
rocketmq.consumer.order.sub.group: order-sub-group
# 访问控制配置
rocketmq.consumer.access-key: producer_user
rocketmq.consumer.secret-key: producer123
rocketmq.consumer.topics:
  - examples-rocketmq-topic
  - order-sub-topic
# 出现问题：invokeSync call the addr[127.0.0.1:19876] timeout，可添加rocketmq.producer.mq-client-api-timeout参数去解决，只是很奇怪，本地部署的集群，默认的3秒就是会超时
# 该参数需要二开rocketmq-spring-boot在org.apache.rocketmq.spring.autoconfigure.RocketMQProperties中新增，还需完善org.apache.rocketmq.spring.autoconfigure包下的自动配置
rocketmq.consumer.mq-client-api-timeout: 15000




